### ISSUE TITLE
make a css file 

### ISSUE THREAD

**Issue by Dishant-Tyagi** [Rahul-BigR/CAD-Project#4]
make a CSS file for login ,register, index page.
you can make a single CSS file or individually file for each html page

**Comment by Rahul-BigR** [comment]
Do the initial commit , as soon you make the page In the main repo ( creating separate folder ) rather then in Project folder

**Comment by Kumud-hasija** [comment]
styling applied

**Comment by Dishant-Tyagi** [comment]
thank you very much,May sir give you good marks
